from enum import Enum

class DataType(Enum):
    FINANCIAL_DATA_AE = "FINANCIAL_DATA_AE"
    FINANCIAL_DATA_CP = "FINANCIAL_DATA_CP"
    FRANCE_RELANCE = "FRANCE_RELANCE"
    FRANCE_2030 = "FRANCE_2030"
    ADEME = 'ADEME'
    REFERENTIEL = "REFERENTIEL"
