include:
  - component: $CI_SERVER_FQDN/csm/gitlab-components/docker-build@5.1.0
    inputs:
      image-name: nocode/data-transform
      image-tag: ${DATA_TRANSFORM_VER}
      build-context: ./
      dockerfile-name: ./app/Dockerfile
      do-login: true
      registry: ${REGISTRY}
      registry-login: ${REGISTRY_USER}
      do-push: true
      enable-debug: true

  - component: $CI_SERVER_FQDN/csm/gitlab-components/docker-build@5.1.0
    inputs:
      image-name: nocode/apis
      image-tag: ${DATA_TRANSFORM_VER}
      build-context: ./
      dockerfile-name: ./apis/Dockerfile
      do-login: true
      registry: ${REGISTRY}
      registry-login: ${REGISTRY_USER}
      do-push: true
      enable-debug: true

  - component: $CI_SERVER_FQDN/csm/gitlab-components/docker-build@5.1.0
    inputs:
      image-name: nocode/batches
      image-tag: ${DATA_TRANSFORM_VER}
      build-context: ./
      dockerfile-name: ./batches/Dockerfile
      do-login: true
      registry: ${REGISTRY}
      registry-login: ${REGISTRY_USER}
      do-push: true
      enable-debug: true

  - component: $CI_SERVER_FQDN/csm/gitlab-components/docker-build@5.1.0
    inputs:
      image-name: nocode/grist-plugins
      image-tag: ${DATA_TRANSFORM_VER}
      build-context: ./
      dockerfile-name: ./grist-plugins/Dockerfile
      do-login: true
      registry: ${REGISTRY}
      registry-login: ${REGISTRY_USER}
      do-push: true
      enable-debug: true

.default-dockerize: &default-dockerize
  rules:
    - if: '$DO_DOCKERIZE == "✅"'
    - if: '$DO_DOCKERIZE == "⚙️"'
      when: manual
    - when: never

"🐳 dockerizing data-transform":
  <<: *default-dockerize
  extends: ".dockerize-nocode/data-transform"
  stage: 🐳 dockerize
  needs: 
    - job: "🐳 dockerizing base image"
      optional: true

"🐳 dockerizing apis":
  <<: *default-dockerize
  extends: ".dockerize-nocode/apis"
  stage: 🐳 dockerize
  needs: 
    - job: "🐳 dockerizing base image"
      optional: true

"🐳 dockerizing batches":
  <<: *default-dockerize
  extends: ".dockerize-nocode/batches"
  stage: 🐳 dockerize
  needs: 
    - job: "🐳 dockerizing base image"
      optional: true

"🐳 dockerizing grist-plugins-dataEtat":
  <<: *default-dockerize
  extends: ".dockerize-nocode/grist-plugins"
  stage: 🐳 dockerize
  needs: 
    - job: "🐳 dockerizing base image"
      optional: true
