"""empty message

Revision ID: 1ed1be1ff3e9
Revises: 20241115_z_wip_sprint_4
Create Date: 2024-12-04 14:27:28.271268

"""
from alembic import op
import sqlalchemy as sa
import logging

# revision identifiers, used by Alembic.
revision = '20241218_a_link_demarches_token'
down_revision = '20241115_z_wip_sprint_4'
branch_labels = None
depends_on = None





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demarches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('demarches_token_id_fkey', 'tokens', ['token_id'], ['id'])

    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), server_default='TRUE', nullable=False))

    # ### end Alembic commands ###


def downgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.drop_column('enabled')

    with op.batch_alter_table('demarches', schema=None) as batch_op:
        batch_op.drop_constraint('demarches_token_id_fkey', type_='foreignkey')
        batch_op.drop_column('token_id')

    # ### end Alembic commands ###


# ###############################################################################
# Boilerplate
#
def _call(name):
    if name not in globals():
        logging.warning(f"Pas de fonction: '{name}'. la migration sera ignorée")
    else:
        globals()[name]()

def upgrade(engine_name):
    fn_name = f"upgrade_{engine_name}"
    _call(fn_name)

def downgrade(engine_name):
    fn_name = f"downgrade_{engine_name}"
    _call(fn_name)

# ###############################################################################