"""empty message

Revision ID: 20250527_themes_grist_columns
Revises: 20250430_add_column_view
Create Date: 2025-05-27 15:39:24.658368

"""
from alembic import op
import sqlalchemy as sa
import logging
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20250527_themes_grist_columns'
down_revision = '20250430_add_column_view'
branch_labels = None
depends_on = None





def upgrade_():
    with op.batch_alter_table('ref_theme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grist_row_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='FALSE', nullable=True))
        batch_op.create_unique_constraint('ref_theme_grist_row_id_key', ['grist_row_id'])


def downgrade_():
    with op.batch_alter_table('ref_theme', schema=None) as batch_op:
        batch_op.drop_constraint('ref_theme_grist_row_id_key', type_='unique')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('grist_row_id')


def upgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


# ###############################################################################
# Boilerplate
#
def _call(name):
    if name not in globals():
        logging.warning(f"Pas de fonction: '{name}'. la migration sera ignorée")
    else:
        globals()[name]()

def upgrade(engine_name):
    fn_name = f"upgrade_{engine_name}"
    _call(fn_name)

def downgrade(engine_name):
    fn_name = f"downgrade_{engine_name}"
    _call(fn_name)

# ###############################################################################