"""empty message

Revision ID: 20250730_programmes_sync_grist
Revises: 20250718_fix_join_qpv_commune
Create Date: 2025-07-30 01:38:47.029059

"""
from alembic import op
import sqlalchemy as sa
import logging

# revision identifiers, used by Alembic.
revision = '20250730_programmes_sync_grist'
down_revision = '20250718_fix_join_qpv_commune'
branch_labels = None
depends_on = None





def upgrade_():
    with op.batch_alter_table('ref_code_programme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grist_row_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), server_default='FALSE', nullable=True))
        batch_op.add_column(sa.Column('synchro_grist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('synchro_grist_id_fkey', 'synchro_grist', ['synchro_grist_id'], ['id'])
        batch_op.create_unique_constraint('ref_code_programme_grist_row_id_key', ['grist_row_id'])


def downgrade_():
    with op.batch_alter_table('ref_code_programme', schema=None) as batch_op:
        batch_op.drop_constraint('ref_code_programme_grist_row_id_key', type_='unique')
        batch_op.drop_constraint('synchro_grist_id_fkey', type_='foreignkey')
        batch_op.drop_column('synchro_grist_id')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('grist_row_id')


def upgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


# ###############################################################################
# Boilerplate
#
def _call(name):
    if name not in globals():
        logging.warning(f"Pas de fonction: '{name}'. la migration sera ignorée")
    else:
        globals()[name]()

def upgrade(engine_name):
    fn_name = f"upgrade_{engine_name}"
    _call(fn_name)

def downgrade(engine_name):
    fn_name = f"downgrade_{engine_name}"
    _call(fn_name)

# ###############################################################################