"""empty message

Revision ID: 20251120_indexes_pour_budget
Revises: 20251020_vm_data_qpv
Create Date: 2025-11-20 16:39:01.666234

"""
from alembic import op
import sqlalchemy as sa
import logging
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20251120_indexes_pour_budget'
down_revision = '20251020_vm_data_qpv'
branch_labels = None
depends_on = None





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
"""
create index index_ffl_programme_theme on flatten_financial_lines(programme_theme);
create index index_ffl_referentielProgrammation_code on flatten_financial_lines("referentielProgrammation_code");
create index index_ffl_source on flatten_financial_lines("source");

create index index_ffl_localisationInterministerielle_code on flatten_financial_lines("localisationInterministerielle_code");
create index index_ffl_localisationInterministerielle_commune_codeRegion on flatten_financial_lines("localisationInterministerielle_commune_codeRegion");
create index index_ffl_localisationInterministerielle_commune_codeEpci on flatten_financial_lines("localisationInterministerielle_commune_codeEpci");
create index index_ffl_localisationInterministerielle_commune_codeDepartement on flatten_financial_lines("localisationInterministerielle_commune_codeDepartement");
create index index_ffl_localisationInterministerielle_commune_code on flatten_financial_lines("localisationInterministerielle_commune_code");
create index index_ffl_localisationInterministerielle_commune_codeCrte on flatten_financial_lines("localisationInterministerielle_commune_codeCrte");
create index index_ffl_localisationInterministerielle_commune_arrondissement_code on flatten_financial_lines("localisationInterministerielle_commune_arrondissement_code");

create index index_ffl_beneficiaire_commune_codeRegion on flatten_financial_lines("beneficiaire_commune_codeRegion");
create index index_ffl_beneficiaire_commune_codeEpci on flatten_financial_lines("beneficiaire_commune_codeEpci");
create index index_ffl_beneficiaire_commune_codeDepartement on flatten_financial_lines("beneficiaire_commune_codeDepartement");
create index index_ffl_beneficiaire_commune_code on flatten_financial_lines("beneficiaire_commune_code");
create index index_ffl_beneficiaire_commune_codeCrte on flatten_financial_lines("beneficiaire_commune_codeCrte");
create index index_ffl_beneficiaire_commune_arrondissement_code on flatten_financial_lines("beneficiaire_commune_arrondissement_code");

create index index_ffl_beneficiaire_categorieJuridique_type on flatten_financial_lines("beneficiaire_categorieJuridique_type");
"""
    )
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
drop index index_ffl_programme_theme;
drop index index_ffl_referentielProgrammation_code;
drop index index_ffl_source;
drop
drop index index_ffl_localisationInterministerielle_code;
drop index index_ffl_localisationInterministerielle_commune_codeRegion;
drop index index_ffl_localisationInterministerielle_commune_codeEpci;
drop index index_ffl_localisationInterministerielle_commune_codeDepartement;
drop index index_ffl_localisationInterministerielle_commune_code;
drop index index_ffl_localisationInterministerielle_commune_codeCrte;
drop index index_ffl_localisationInterministerielle_commune_arrondissement_code;
drop
drop index index_ffl_beneficiaire_commune_codeRegion;
drop index index_ffl_beneficiaire_commune_codeEpci;
drop index index_ffl_beneficiaire_commune_codeDepartement;
drop index index_ffl_beneficiaire_commune_code;
drop index index_ffl_beneficiaire_commune_codeCrte;
drop index index_ffl_beneficiaire_commune_arrondissement_code;
drop
drop index index_ffl_beneficiaire_categorieJuridique_type;
"""
    )


def upgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def upgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


# ###############################################################################
# Boilerplate
#
def _call(name):
    if name not in globals():
        logging.warning(f"Pas de fonction: '{name}'. la migration sera ignorée")
    else:
        globals()[name]()

def upgrade(engine_name):
    fn_name = f"upgrade_{engine_name}"
    _call(fn_name)

def downgrade(engine_name):
    fn_name = f"downgrade_{engine_name}"
    _call(fn_name)

# ###############################################################################