"""Ajout colonne `code_departement` sur ref_centre_couts et création table ref_departement

Revision ID: 20260302_add_code_departement_centre_couts
Revises: 20260219_shared_queuedcol
Create Date: 2026-03-02 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import logging
from datetime import datetime
from pathlib import Path


# revision identifiers, used by Alembic.
revision = '20260302_add_cdpt_c_couts'
down_revision = '20260219_shared_queuedcol'
branch_labels = None
depends_on = None


# The department data is stored in a SQL file placed in a sibling `new/` directory
def _execute_departements_sql():
    data_folder = Path(__file__).resolve().parent / Path(__file__).stem / "new"
    sql_path = data_folder / "departements.sql"
    if not sql_path.exists():
        logging.warning(f"Departements SQL not found: {sql_path}")
        return
    sql_text = sql_path.read_text(encoding="utf-8")
    # Execute raw SQL which inserts the departments
    op.execute(sa.text(sql_text))


def upgrade_():
    # Création de la table ref_departement
    op.create_table(
        'ref_departement',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.String(), nullable=False),
        sa.Column('label', sa.String(), nullable=True),
        sa.Column('code_region', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['code_region'], ['ref_region.code'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    
    # Insertion des départements
    departement_table = sa.table(
        'ref_departement',
        sa.column('code', sa.String),
        sa.column('label', sa.String),
        sa.column('code_region', sa.String),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime),
    )
    
    # Exécute le SQL d'insertion des départements
    _execute_departements_sql()

    # # Ajout de la colonne code_departement sur ref_centre_couts
    with op.batch_alter_table('ref_centre_couts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_departement', sa.String(length=5), nullable=True))


def downgrade_():
    # Suppression de la colonne code_departement sur ref_centre_couts
    with op.batch_alter_table('ref_centre_couts', schema=None) as batch_op:
        batch_op.drop_column('code_departement')
    
    # Suppression de la table ref_departement
    op.drop_table('ref_departement')


def upgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


# ###############################################################################
# Boilerplate
#
def _call(name):
    if name not in globals():
        logging.warning(f"Pas de fonction: '{name}'. la migration sera ignorée")
    else:
        globals()[name]()

def upgrade(engine_name):
    fn_name = f"upgrade_{engine_name}"
    _call(fn_name)

def downgrade(engine_name):
    fn_name = f"downgrade_{engine_name}"
    _call(fn_name)

# ###############################################################################
