"""empty message

Revision ID: e8347058a739
Revises: 20260120_delete_themes
Create Date: 2026-01-27 14:39:34.336176

"""
from alembic import op
import sqlalchemy as sa
import logging

# revision identifiers, used by Alembic.
revision = '20260126_evol_qpv_lieu_action'
down_revision = '20260120_delete_themes'
branch_labels = None
depends_on = None





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qpv_lieu_action', schema=None) as batch_op:
        batch_op.alter_column("annee", new_column_name="annee_exercice")
        batch_op.alter_column("code_reference", new_column_name="ref_action")
        batch_op.alter_column("n_ej", new_column_name="ej")
        batch_op.alter_column("ratio_montant", new_column_name="montant_ventille")

        batch_op.add_column(sa.Column('libelle_action', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('siret', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_qpv_lieu_action_metier', ['annee_exercice', 'ref_action', 'ej', 'code_qpv'])
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qpv_lieu_action', schema=None) as batch_op:
        batch_op.drop_constraint('uq_qpv_lieu_action_metier', type_='unique')
        batch_op.drop_column('siret')
        batch_op.drop_column('libelle_action')

        batch_op.alter_column("montant_ventille", new_column_name="ratio_montant")
        batch_op.alter_column("ej", new_column_name="n_ej")
        batch_op.alter_column("ref_action", new_column_name="code_reference")
        batch_op.alter_column("annee_exercice", new_column_name="annee")
    # ### end Alembic commands ###


def upgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


# ###############################################################################
# Boilerplate
#
def _call(name):
    if name not in globals():
        logging.warning(f"Pas de fonction: '{name}'. la migration sera ignorée")
    else:
        globals()[name]()

def upgrade(engine_name):
    fn_name = f"upgrade_{engine_name}"
    _call(fn_name)

def downgrade(engine_name):
    fn_name = f"downgrade_{engine_name}"
    _call(fn_name)

# ###############################################################################