"""empty message

Revision ID: 20260323_ref_action_nullable
Revises: 20260306_add_grist_columns
Create Date: 2026-03-23 13:26:03.047707

"""
from alembic import op
import sqlalchemy as sa
import logging
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260323_ref_action_nullable'
down_revision = '20260306_add_grist_columns'
branch_labels = None
depends_on = None





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qpv_lieu_action', schema=None) as batch_op:
        batch_op.alter_column('ref_action',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('libelle_action',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_qpv_lieu_action_metier'), type_='unique')
        batch_op.create_unique_constraint('uq_qpv_lieu_action_metier', ['annee_exercice', 'ej', 'code_qpv', 'libelle_action'])

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qpv_lieu_action', schema=None) as batch_op:
        batch_op.drop_constraint('uq_qpv_lieu_action_metier', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_qpv_lieu_action_metier'), ['annee_exercice', 'ref_action', 'ej', 'code_qpv'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('libelle_action',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('ref_action',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def upgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


# ###############################################################################
# Boilerplate
#
def _call(name):
    if name not in globals():
        logging.warning(f"Pas de fonction: '{name}'. la migration sera ignorée")
    else:
        globals()[name]()

def upgrade(engine_name):
    fn_name = f"upgrade_{engine_name}"
    _call(fn_name)

def downgrade(engine_name):
    fn_name = f"downgrade_{engine_name}"
    _call(fn_name)

# ###############################################################################