"""20260119_add_tus_audit

Revision ID: 86fd1a1335f2
Revises: 20251211_export_financial_task
Create Date: 2026-01-19 11:07:23.234032

"""
from alembic import op
import sqlalchemy as sa
import logging

# revision identifiers, used by Alembic.
revision = '20260119_add_tus_audit'
down_revision = '20251211_export_financial_task'
branch_labels = None
depends_on = None

def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_insert_financial_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token', sa.String(), nullable=True))
        batch_op.alter_column('fichier_ae',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('fichier_cp',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_unique_constraint(None, ['session_token'])
    # ### end Alembic commands ###


def downgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_insert_financial_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('fichier_cp',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('fichier_ae',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('session_token')

    # ### end Alembic commands ###


def upgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


# ###############################################################################
# Boilerplate
#
def _call(name):
    if name not in globals():
        logging.warning(f"Pas de fonction: '{name}'. la migration sera ignorée")
    else:
        globals()[name]()

def upgrade(engine_name):
    fn_name = f"upgrade_{engine_name}"
    _call(fn_name)

def downgrade(engine_name):
    fn_name = f"downgrade_{engine_name}"
    _call(fn_name)

# ###############################################################################