"""empty message

Revision ID: 20260120_delete_themes
Revises: 20260110_audit_remote_files
Create Date: 2026-01-20 16:57:24.773273

"""
from alembic import op
import sqlalchemy as sa
import logging
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20260120_delete_themes'
down_revision = '20260110_audit_remote_files'
branch_labels = None
depends_on = None





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def upgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade_audit():
    pass


def upgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('share_preference_preference_id_fkey', 'share_preference', type_='foreignkey')
    op.create_foreign_key(
        'share_preference_preference_id_fkey',
        'share_preference',
        'preference_users',
        ['preference_id'],
        ['id'],
        ondelete='CASCADE'
    )
    
    #
    # Ici, décision a été prise de supprimer les filtres ayant des thèmes en leur sein.
    #
    op.execute(
        """
delete
from preference_users pu 
where (filters->'theme') is not null or (filters->'themes') is not null;
        """
    )

    # ### end Alembic commands ###


def downgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('share_preference_preference_id_fkey', 'share_preference', type_='foreignkey')
    op.create_foreign_key(
        'share_preference_preference_id_fkey',
        'share_preference',
        'preference_users',
        ['preference_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def upgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


# ###############################################################################
# Boilerplate
#
def _call(name):
    if name not in globals():
        logging.warning(f"Pas de fonction: '{name}'. la migration sera ignorée")
    else:
        globals()[name]()

def upgrade(engine_name):
    fn_name = f"upgrade_{engine_name}"
    _call(fn_name)

def downgrade(engine_name):
    fn_name = f"downgrade_{engine_name}"
    _call(fn_name)

# ###############################################################################