"""Recréation des vues pour ajouter centre_couts_code_departement

Revision ID: 20260302_update_views_add_cdpt
Revises: 20260302_add_cdpt_c_couts
Create Date: 2026-03-02 11:30:00.000000

"""
from alembic import op
import logging
from pathlib import Path

# revision identifiers, used by Alembic.
revision = '20260302_update_views_add_cdpt'
down_revision = '20260302_add_cdpt_c_couts'
branch_labels = None
depends_on = None

_data_folder = Path(__file__).resolve().parent / Path(__file__).stem


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    logging.info("=== Recreating views (add centre_couts_code_departement) ===")
    op.execute(_new_filecontent("flatten_ae.sql"))
    op.execute(_new_filecontent("flatten_ademe.sql"))
    op.execute(_new_filecontent("flatten_orphan_cp.sql"))
    op.execute(_new_filecontent("flatten_financial_lines.sql"))
    logging.info("=== Views recreated ===")

    logging.info("=== Recreating Materialized views ===")
    op.execute(_new_filecontent("alter_view.sql"))
    logging.info("=== Materialized views recreated ===")
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    logging.info("No downgrade_. We keep views (manual rollback if needed)")
    # ### end Alembic commands ###


def upgrade_audit():
    pass


def downgrade_audit():
    pass


def upgrade_settings():
    pass


def downgrade_settings():
    pass


def upgrade_demarches_simplifiees():
    pass


def downgrade_demarches_simplifiees():
    pass


def _new_filecontent(name: str):
    p = _data_folder / "new" / name
    with p.open("r") as f:
        return f.read()



# ###############################################################################
# Boilerplate
#
def _call(name):
    if name not in globals():
        logging.warning(f"Pas de fonction: '{name}'. la migration sera ignorée")
    else:
        globals()[name]()


def upgrade(engine_name):
    fn_name = f"upgrade_{engine_name}"
    _call(fn_name)


def downgrade(engine_name):
    fn_name = f"downgrade_{engine_name}"
    _call(fn_name)

# ###############################################################################
