DEBUG: info|debug|False

# Connexion à la BDD principal de Chorus
SQLALCHEMY_DATABASE_URI: "postgresql+psycopg://postgres:password@localhost:5432/<DBNAME>"

# préciser les connections au BDD d'audit et de settings
SQLALCHEMY_BINDS:
  audit: #schema audit
    url: "postgresql+psycopg://postgres:password@localhost:5432/<DBNAME>?options=-c%20search_path=audit"
    pool_pre_ping: True
    pool_recycle: 30
  settings: #schema audit
    url: "postgresql+psycopg://postgres:password@localhost:5432/<DBNAME>?options=-c%20search_path=settings"
    pool_pre_ping: True
    pool_recycle: 30
  demarches_simplifiees:
    url: "postgresql+psycopg://postgres:password@localhost:5432/<DBNAME>?options=-c%20search_path=demarches_simplifiees"
    pool_pre_ping: True
    pool_recycle: 30



GRIST:
  DATABASE_URL: "postgresql+psycopg://postgres:password@localhost:5432/grist"
  SERVEUR_URL: "https://grist.nocode.csm.ovh"
  TOKEN_SCIM: "<TOKEN SCIM>"
  TOKEN_SYNC_DB: "<TOKEN_SYNC_DB>"

SQLALCHEMY_ENGINE_OPTIONS:
  pool_pre_ping: True
  pool_recycle: 30

#CONFIG CELERY REDIS
CELERY_BROKER_URL: 'redis://localhost:6379/1'
result_backend: "db+postgresql+psycopg://postgres:password@localhost:5432/<DBNAME_TASK>"
result_extended: True
task_track_started: True
max_queue_size: 100 # nombre de message max en attente dans une file redis
timeout_queue_retry: 60

# SECRET KEY OIDC Keycloak
SECRET_KEY: "OIDC"

# Checmin de stockage des fichiers uploader
UPLOAD_FOLDER: "<PATH_FOLDER>"
# nombre de ligne par fichier max à traiter
SPLIT_FILE_LINE: 100000
IMPORT_BATCH_SIZE: 10


# CONFIGURATION OPENID Keycloak pour la securation des endpoints
KEYCLOAK_OPENID:
  URL: <url>
  SECRET_KEY: "<secret key>"
  REALM: <realm>
  CLIENT_ID: "client_id"

redis_applicatif:
  host: <host>
  port: 6379
  db: <DB>

# CONFIGURATION pour keycloak ADMIN (gestion des utilisateurs)
KEYCLOAK_ADMIN:
  URL: <url>
  SECRET_KEY: "<secret key>"
  REALM: <realm>

ERROR_INCLUDE_MESSAGE: False

# ICI API pour les appels en mode batch (utilisé un API auto heberger.)
API_ENTREPRISE_BATCH:
  URL: <AUTRE API>
  TOKEN: <token d'authentification>
  CONTEXT: <CONTEXTE>
  RECIPIENT: <RECIPIENT> # siret du sib
  OBJECT: <OBJECT>

API_DEMARCHE_SIMPLIFIE:
  URL: DMS_URL

FERNET_SECRET_KEY: "<fernet_secret_key>"

# COnfiguration SMTP pour envoi de mail
SMTP:
  server: ""
  port: 465
  from_email: ""
  pwd: "password"
  use_ssl: True

#  CONFIGURATION de Nocodb
NOCODB_URL: "<url>"
NOCODB_PROJECT:
  # Lister ici les projet et les token associés aux projets
  PROJECT: TOKEN_API
  PROJECT_2: TOKEN_API_PROJECT

ressources:
  default:
    "graphiques": "http://localhost:8088/"
    "api_swagger": "http://localhost:5000/budget/api/v1"
    "documentation": "https://github.com/dataregion/DataEtatRegion-docs/blob/main/budget/DataEtatBretagne_Notice-utilisation-Budget_032023.pdf"
    "suivi_usage": ""
    "grist": "https://grist.nocode.csm.ovh/o/docs/login?next=%2F"

  "053":
    "visuterritoire": "https://geobretagne.fr/mviewer/?config=/apps/visuterritoire/config.xml"
    "graphiques": "http://localhost:8088/"
    "api_swagger": "http://localhost:5000/budget/api/v1"
    "documentation": "https://github.com/dataregion/DataEtatRegion-docs/blob/main/budget/DataEtatBretagne_Notice-utilisation-Budget_032023.pdf"
    "suivi_usage": ""
    "grist": "https://grist.nocode.csm.ovh/o/docs/login?next=%2F"