 CREATE MATERIALIZED VIEW vt_budget_summary AS
   SELECT vt_flatten_summarized_ae.id,
      vt_flatten_summarized_ae.annee,
      concat(vt_flatten_summarized_ae.source, '_', vt_flatten_summarized_ae.source_region) AS source,
      vt_flatten_summarized_ae.montant_ae,
      vt_flatten_summarized_ae.montant_cp,
      vt_flatten_summarized_ae.code_programme,
      vt_flatten_summarized_ae.siret,
      vt_flatten_summarized_ae.code_commune,
      vt_flatten_summarized_ae.code_departement,
      vt_flatten_summarized_ae.code_crte,
      vt_flatten_summarized_ae.code_epci,
      vt_flatten_summarized_ae.code_qpv,
      vt_flatten_summarized_ae.code_qpv24,
      vt_flatten_summarized_ae.categorie_juridique,
      vt_flatten_summarized_ae.loc_inter,
      vt_flatten_summarized_ae.code_departement_loc_inter,
      vt_flatten_summarized_ae.code_commune_loc_inter,
      vt_flatten_summarized_ae.code_epci_loc_inter,
      vt_flatten_summarized_ae.code_crte_loc_inter
      FROM vt_flatten_summarized_ae
   UNION
   SELECT vt_flatten_summarized_ademe.id,
      vt_flatten_summarized_ademe.annee,
      vt_flatten_summarized_ademe.source,
      vt_flatten_summarized_ademe.montant_ae,
      vt_flatten_summarized_ademe.montant_cp,
      vt_flatten_summarized_ademe.code_programme,
      vt_flatten_summarized_ademe.siret,
      vt_flatten_summarized_ademe.code_commune,
      vt_flatten_summarized_ademe.code_departement,
      vt_flatten_summarized_ademe.code_crte,
      vt_flatten_summarized_ademe.code_epci,
      vt_flatten_summarized_ademe.code_qpv,
      vt_flatten_summarized_ademe.code_qpv24,
      vt_flatten_summarized_ademe.categorie_juridique,
      vt_flatten_summarized_ademe.loc_inter,
      vt_flatten_summarized_ademe.code_departement_loc_inter,
      vt_flatten_summarized_ademe.code_commune_loc_inter,
      vt_flatten_summarized_ademe.code_epci_loc_inter,
      vt_flatten_summarized_ademe.code_crte_loc_inter
      FROM vt_flatten_summarized_ademe;