FROM python:3.12.6-alpine@sha256:7130f75b1bb16c7c5d802782131b4024fe3d7a87ce7d936e8948c2d2e0180bc4


RUN pip install pip-tools

# Installer dépendances système communes (Postgres libs, gcc, musl-dev...)
RUN apk add --no-cache postgresql-libs \
    && apk add --no-cache --virtual .build-deps gcc gdal gdal-dev gdal-tools proj proj-dev proj-util geos geos-dev musl-dev postgresql-dev

# Installer pip-tools (common Python deps)
RUN pip install pip-tools

WORKDIR /appli