FROM ghcr.io/astral-sh/uv:0.11.20-python3.13-trixie-slim@sha256:237f21ec146a3c45b5a14ab531607648868c6062064b80a0f5313956d96c3f1c AS builder

WORKDIR /build
# Copie du projet
COPY . .

RUN apt update && apt install -y git

# Prépare les venv de dev des différentes applications
RUN cd app/ && \
    uv venv && \
    uv pip install .[dev] -r requirements.external.txt && pip install -r requirements.editable.txt --no-deps && \
    cd ..

RUN cd apis/ && \
    uv venv && \
    uv pip install .[dev] -r requirements.external.txt && pip install -r requirements.editable.txt --no-deps && \
    cd ..

RUN cd batches/ && \
    uv venv && \
    uv pip install .[dev] -r requirements.external.txt && pip install -r requirements.editable.txt --no-deps && \
    cd ..

RUN cd tests_e2e/ && \
    uv venv && \
    uv pip install .[dev] && \
    cd ..

RUN cd grist-plugins/ && \
    uv venv && \
    uv pip install .[dev] -r requirements.external.txt && pip install -r requirements.editable.txt --no-deps && \
    cd ..

RUN cd services/ && \
    uv venv && \
    SERVICES_IS_TRANSITIVE_DEP=0 uv pip install .[dev] && \
    cd ..

RUN cd models/ && \
    uv venv && \
    uv pip install .[dev] && \
    cd ..

RUN cd gristcli/ && \
    uv venv && \
    uv pip install .[dev] && \
    cd ..

RUN cd supersetcli/ && \
    uv venv && \
    uv pip install .[dev] && \
    cd ..

FROM ghcr.io/astral-sh/uv:0.11.20-python3.13-trixie-slim@sha256:237f21ec146a3c45b5a14ab531607648868c6062064b80a0f5313956d96c3f1c

WORKDIR /build

COPY --from=builder /build/app/.venv /build/app/.venv
COPY --from=builder /build/apis/.venv /build/apis/.venv
COPY --from=builder /build/batches/.venv /build/batches/.venv
COPY --from=builder /build/grist-plugins/.venv /build/grist-plugins/.venv
COPY --from=builder /build/tests_e2e/.venv /build/tests_e2e/.venv
COPY --from=builder /build/services/.venv /build/services/.venv
COPY --from=builder /build/models/.venv /build/models/.venv
COPY --from=builder /build/gristcli/.venv /build/gristcli/.venv
COPY --from=builder /build/supersetcli/.venv /build/supersetcli/.venv