# yaml-language-server: $schema=./apis-config.schema.json
print_sql: true

sqlalchemy_database_uri: "postgresql+psycopg://postgres:password@localhost:5432/<DBNAME>"
sqlalchemy_database_uri_audit: "postgresql+psycopg://postgres:passwd@localhost:5432/<DBNAME_AUDIT>"
sqlalchemy_database_uri_settings: "postgresql+psycopg://postgres:passwd@localhost:5432/<DBNAME_SETTINGS>"

dossier_des_exports: "<CHEMIN_DES_EXPORTS>"

keycloak_openid:
  url: http://localhost:8080
  realm: <REALM>
  client_id: <CLIENT_ID>
  secret_key: <SECRET_KEY>
  test_user: <TEST_USER>
  test_password: <TEST_PASSWORD>

keycloak_administrator:
  url: http://localhost:8080
  realm: <REALM>
  client_id: <CLIENT_ID>
  secret_key: <SECRET_KEY>
  test_user: <TEST_USER>
  test_password: <TEST_PASSWORD>

cache_config:
  budget_totaux_enabled: true

redis_applicatif:
  host: <host>
  port: 6379
  db: <DB>

api_data_subventions:
  url: <URL>
  token: <TOKEN>

##
api_entreprise:
  url: https://staging.entreprise.api.gouv.fr
  token: <token d'authentification>

  context: nocode-budget.localhost
  recipient: 26350579400028
  object: nocode-budget.localhost

  timeout_seconds: 30

##
##
api_entreprise_batch:
  url: <URL>
  token: 
  context: nocode-budget.localhost
  recipient: 26350579400028
  object: nocode-budget.localhost
  
  timeout_seconds: 5

token_for_grist_plugins: "<TOKEN>"

# Configuration pour le Go TO SUPERSET
to_superset_config:
  url_superset: "http://localhost" #l'url public du superset
  user_superset_tech_login: "<USER_LOGIN>" # l'utilisateur technique Superset (qui a les droits admin)
  user_superset_tech_password: "<USER_PASSWORD>" #son password
  superset_database_id: 1 #L'Id de la datasource où les datasets seront créé


# UPLOAD
upload :
  tus_folder: <chemin_dossier_upload_tus> #dossier temporaire pour les uploads tus
  final_folder: <chemin_dossier_upload_final> #Dossier où seront mis les fichiers budgets chorus à traiter