"""empty message

Revision ID: f6eb760678c1
Revises: 4af5d1e78b3e
Create Date: 2023-08-31 17:37:49.886889

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f6eb760678c1'
down_revision = '4af5d1e78b3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_qpv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('label_commune', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )

    with op.batch_alter_table('ref_siret', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_qpv', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'ref_qpv', ['code_qpv'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ref_siret', schema=None) as batch_op:
        batch_op.drop_column('code_qpv')

    op.drop_table('ref_qpv')
    # ### end Alembic commands ###
