"""empty message

Revision ID: 20241209_fix_id_donnees_ds
Revises: 20241009_reconciliation_2
Create Date: 2024-09-12 15:40:42.532039

"""

from alembic import op
import sqlalchemy as sa
import logging


# revision identifiers, used by Alembic.
revision = "20241209_fix_id_donnees_ds"
down_revision = "20241009_reconciliation_2"
branch_labels = None
depends_on = None


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("donnees", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id_ds", sa.String(), nullable=False))
        batch_op.create_index(batch_op.f("ix_donnees_id_ds"), ["id_ds"], unique=True)

    # ### end Alembic commands ###


def downgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("donnees", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_donnees_id_ds"))
        batch_op.drop_column("id_ds")

    # ### end Alembic commands ###


# ###############################################################################
# Boilerplate
#
def _call(name):
    if name not in globals():
        logging.warning(f"Pas de fonction: '{name}'. la migration sera ignorée")
    else:
        globals()[name]()


def upgrade(engine_name):
    fn_name = f"upgrade_{engine_name}"
    _call(fn_name)


def downgrade(engine_name):
    fn_name = f"downgrade_{engine_name}"
    _call(fn_name)


# ###############################################################################
