"""

Revision ID: 20240529_improve_ademe
Revises: 20240325_b_vt_add_source_region
Create Date: 2024-05-29

"""
from pathlib import Path
from alembic import op
import logging

# revision identifiers, used by Alembic.
revision = "20240529_improve_ademe"
down_revision = "20240325_b_vt_add_source_region"
branch_labels = None
depends_on = None

_data_folder = Path(__file__).resolve().parent / __name__


def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    logging.info("Mise à jour de valeurs par défaut dans la vue flatten_ademe")
    op.execute(_filecontent("flatten_ademe.sql"))

    logging.info("Refresh de la VM contenant les champs impliqués")
    op.execute("REFRESH MATERIALIZED VIEW public.flatten_financial_lines;")
    # Pas de refresh de vt_flatten_summarized_ademe car ne contient pas les champs impliqués
    
    logging.info("Finished")
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_audit():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_settings():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_demarches_simplifiees():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


# ###############################################################################
# Boilerplate
#
def _call(name):
    if name not in globals():
        logging.warning(f"Pas de fonction: '{name}'. la migration sera ignorée")
    else:
        globals()[name]()


def upgrade(engine_name):
    fn_name = f"upgrade_{engine_name}"
    _call(fn_name)


def downgrade(engine_name):
    fn_name = f"downgrade_{engine_name}"
    _call(fn_name)


# ###############################################################################

def _filecontent(name: str):
    """Get file content from ./`modulename`/name"""
    p = _data_folder / name
    with p.open("r") as f:
        view_str = f.read()
    return view_str
