"""

Revision ID: 20240122_france2030
Revises: 20231220_hf_vues_materialisees
Create Date: 2024-01-15 16:34:15.465752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20240122_france2030"
down_revision = "20231220_hf_vues_materialisees"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("france_2030", schema=None) as batch_op:
        batch_op.add_column(sa.Column("annee", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("france_2030", schema=None) as batch_op:
        batch_op.drop_column("annee")
    # ### end Alembic commands ###
