"""empty message

Revision ID: 20240212_zzzz_col_username
Revises: 20240212_zzz_delayed_ins_tasks
Create Date: 2024-02-13 09:29:39.538706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20240212_zzzz_col_username"
down_revision = "20240212_zzz_delayed_ins_tasks"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_insert_financial_tasks", schema="audit") as batch_op:
        batch_op.add_column(sa.Column("username", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_insert_financial_tasks", schema="audit") as batch_op:
        batch_op.drop_column("username")
    # ### end Alembic commands ###
