default:
  # client_metadata:
    # client_id: data-transform-back
    # client_secret: BPQMXHnecdwp2xWwiSK3ILnOLs0uxBM8
  client_metadata:
    realm: Regions
    client_id: data-transform-back
  provider_metadata:
    issuer: http://localhost:8080/realms/Regions
    authorization_endpoint: http://localhost:8080/realms/Regions/protocol/openid-connect/auth
    userinfo_endpoint: http://localhost:8080/realms/Regions/protocol/openid-connect/userinfo
    token_endpoint: http://localhost:8080/realms/Regions/protocol/openid-connect/token
    introspection_endpoint: http://localhost:8080/realms/Regions/protocol/openid-connect/token/introspect
    jwks_endpoint: http://localhost:8080/realms/Regions/protocol/openid-connect/certs

# default:
#   client_metadata:
#     client_id: back-api
#     client_secret: hNFljZDqcKehP0qJiB82VP6wxKRuu1RC
#   provider_metadata:
#     issuer: https://auth.nocode.csm.ovh/realms/Regions
#     authorization_endpoint: https://auth.nocode.csm.ovh/realms/Regions/protocol/openid-connect/auth
#     userinfo_endpoint: https://auth.nocode.csm.ovh/realms/Regions/protocol/openid-connect/userinfo
#     token_endpoint: https://auth.nocode.csm.ovh/realms/Regions/protocol/openid-connect/token
#     introspection_endpoint: https://auth.nocode.csm.ovh/realms/Regions/protocol/openid-connect/token/introspect
